### ISSUE TITLE
The animation from the sync result didn't match very good.

### ISSUE THREAD

**Issue by git4sun** [DanielSWolf/rhubarb-lip-sync#24]
I took a piece of speech and use rhubarb to extract the mouth shape and put the mouth shape change into an animation video. It seems to match for less than 50% of the speech. Would you mind take a look what's wrong? [The animated video](https://youtu.be/NMOq1XeYoNU)

> 0.00	X
0.56	C
0.79	B
1.37	        D
1.57	        C
......

I just put the mouth shape X from 0 to 0.56 seconds and C from 0.56 to 0.79 seconds. Is that the right way of creating the animation? I feel like the sample rate is a bit low since when the speech speed is fast many syllables are not recognized. Is there an option to adjust the sampling rate?

Thanks

**Comment by DanielSWolf** [comment]
The lip-sync in that video is indeed not great. However, that has nothing to do with the frame rate. Rhubarb uses a frame rate of 100fps internally. So if it tells you to hold the C mouth from 0.56s to 0.79s, that means that it deliberately decided to hold that mouth for 23 internal frames.

The real problem seems to be that Rhubarb has trouble understanding the dialog. Try using the `--dialogFile` option to tell Rhubarb what dialog to expect. For best results, cut the audio into small clips with no more than two or three sentences per clip.

Let me know if that helps!

**Comment by amu340** [comment]
Hi, I would like to use rhubarb to extract the mouth shape on the real time audio stream, but I don't know how to do this? I have downloaded the source code, but I can find the Makefile. How can I build the project by myself.

**Comment by DanielSWolf** [comment]
@amu340: Please search existing issues or create a new one. Your problem doesn't seem to be related to this issue.
