### ISSUE TITLE
animation speed looks slow

### ISSUE THREAD

**Issue by mityok** [DanielSWolf/rhubarb-lip-sync#28]
Hello,
I've created small [demo](https://jsfiddle.net/mityok/aqjupoar/3/) using the library, both with and without using dialogFile, and the end result looks like it skipping frames.
is there i possibility to specify sensitivity or mouth motion speed?
thank you very much.

**Comment by DanielSWolf** [comment]
Your demo looks good to me. Yes, it does look a bit static, but that's because you're only showing the mouth, and you're showing it rather large. Add a face around it, maybe some facial animation, camera movement etc., and it will look good!

For comparison, have a look at some classic animated cartoons such as [Disney's Gummi Bears](https://www.youtube.com/watch?v=bF5qPO4PgkU). At the time, Disney had the best animators there were. But concentrate on the mouths alone, and you will see that they look just as static as your demo. That's because most classic cartoons limit themselves to the same 6-9 mouth shapes Rhubarb uses. And you can't get more fluid results with so few mouth shapes.

It is possible to get absolutely fluid animated mouths. Just look at Disney's animated feature films, such as [Aladdin](https://www.youtube.com/watch?v=wIGqHxwzjGA). But to get there, you'll need *much more* than 6-9 fixed mouth shapes!

**Comment by mityok** [comment]
thank you for your suggestion, i was wondering if it's possible to have more than 9 mouth shapes?
i've been playing with amazon polly API and they provide 17 visemes, so it looks a bit more natural

**Comment by DanielSWolf** [comment]
Adding more (optional) mouth shapes is a good idea. Thanks, by the way, for pointing me to the Polly API; I didn't know that one.

At the moment, however, my main goal is to get the current style of animation working in all situations. There are still problems with fast speech and with certain voices (mostly female). Plus, I'd like to add multi-language support.

Once these things are done, I might look at more "fluent" animation. But don't count on it any time soon!

**Comment by DanielSWolf** [comment]
I'm closing this for now. I might revisit it another time.
