### ISSUE TITLE
How does --dialogFile work?

### ISSUE THREAD

**Issue by manxueitp** [DanielSWolf/rhubarb-lip-sync#4]
I'm now working on a project which need to grab mouth shape info from an audio. I already did the sound recognition and get the script by using sphinx. I'd like to use rhubarb to get the mouth shape but instead of taking the audio as input, I'm wondering if I can use the script which I already got from sphinx. I noticed this " -d <path>, --dialogFile " but I don't know what's the file like. It will be helpful if you can tell more about dialogFile. Does it have time info matches with the script in dialogFile?  It will be great if there's an example or more reference for the dialogFile. Any suggestions or advice will be helpful, really appreciate!

**Comment by DanielSWolf** [comment]
Hi @manxueitp,

First, it it *not* possible to run Rhubarb without giving it an audio file. This is because Rhubarb does multiple analysis passes over the file: It performs voice activity detection, word recognition, phone alignment, and future versions may perform additional analysis steps. Each of these steps requires access to the audio file. Giving Rhubarb only the result of word recognition isn't enough.

The reason for your question may be that you want to improve performance, not performing word recognition twice. In this case, you can simply pass a `--logFile` argument to Rhubarb. In this log file, you'll find -- among other things -- the full recognized dialog, so you don't have to call Sphinx yourself.

Regarding the `--dialogFile` option: This is meant for situations where you know the dialog text in advance. You specify a plain text file containing the dialog of the audio file, *without* any timestamps. Rhubarb will still perform word recognition, but it will prefer words and phrases that occur in the dialog file, leading to better recognition results. For instance, let's say you're recording dialog for a computer game. The script says: "Hi, my name is Raphael." But actually, the voice artist only says "My name is Raphael", dropping the "Hi". If you specify a dialog file with the original line ("Hi, my name is Raphael."), this will still allow Rhubarb to get better results, including the name "Raphael".

**Comment by manxueitp** [comment]
Hi Daniel,
Thanks for the quick and comprehensive response, super helpful!
