### ISSUE TITLE
Different results on OSX vs linux

### ISSUE THREAD

**Issue by brettharrisonzya** [DanielSWolf/rhubarb-lip-sync#42]
I am getting different results on OSX vs linux, should this be expected?
OSX is the better result.

Linux:
{
  "metadata": {
    "soundFile": "audio.wav",
    "duration": 3.56
  },
  "mouthCues": [
    { "start": 0.00, "end": 0.09, "value": "X" },
    { "start": 0.09, "end": 0.30, "value": "B" },
    { "start": 0.30, "end": 0.37, "value": "C" },
    { "start": 0.37, "end": 0.44, "value": "B" },
    { "start": 0.44, "end": 0.51, "value": "C" },
    { "start": 0.51, "end": 0.72, "value": "D" },
    { "start": 0.72, "end": 0.80, "value": "C" },
    { "start": 0.80, "end": 1.12, "value": "X" },
    { "start": 1.12, "end": 1.26, "value": "B" },
    { "start": 1.26, "end": 1.54, "value": "C" },
    { "start": 1.54, "end": 2.83, "value": "X" },
    { "start": 2.83, "end": 2.89, "value": "C" },
    { "start": 2.89, "end": 3.09, "value": "G" },
    { "start": 3.09, "end": 3.23, "value": "B" },
    { "start": 3.23, "end": 3.56, "value": "X" }
  ]
}

OSX:
{
  "metadata": {
    "soundFile": "audio.wav",
    "duration": 3.56
  },
  "mouthCues": [
    { "start": 0.00, "end": 0.09, "value": "X" },
    { "start": 0.09, "end": 0.30, "value": "B" },
    { "start": 0.30, "end": 0.37, "value": "C" },
    { "start": 0.37, "end": 0.44, "value": "B" },
    { "start": 0.44, "end": 0.51, "value": "C" },
    { "start": 0.51, "end": 0.72, "value": "D" },
    { "start": 0.72, "end": 0.80, "value": "C" },
    { "start": 0.80, "end": 1.12, "value": "X" },
    { "start": 1.12, "end": 1.26, "value": "B" },
    { "start": 1.26, "end": 1.54, "value": "C" },
    { "start": 1.54, "end": 2.30, "value": "X" },
    { "start": 2.30, "end": 2.46, "value": "B" },
    { "start": 2.46, "end": 2.60, "value": "D" },
    { "start": 2.60, "end": 2.67, "value": "B" },
    { "start": 2.67, "end": 2.88, "value": "C" },
    { "start": 2.88, "end": 3.02, "value": "B" },
    { "start": 3.02, "end": 3.56, "value": "X" }
  ]
}

**Comment by DanielSWolf** [comment]
My guess is that the differences you're observing aren't based on the operating system. Rhubarb uses multithreading to speed up the processing. It is purely random which thread will receive which audio segments in what order. This means that animating the same recording with the same settings may give slightly different results each time, even on the same machine.

To test my assumption, you can disable multithreading by passing `--threads 1` on the command line. This should give deterministic results, and the output should be identical on any OS.

**Comment by brettharrisonzya** [comment]
Ok so --threads 1 produces the same results on both OSX and linux, but the result are not as accurate.  OSX makes the best results when I do not specify --threads at all.

**Comment by DanielSWolf** [comment]
I see. From the looks of your output, your audio file consists of two segments of speech with a short pause inbetween. When using singlethreading, both segments are fed to the same speech recognizer, one after the other. In theory, this should allow the recognizer to learn from the first segment, then produce better results for the second. In practice, there may be cases where the opposite is the case. I believe this is what you're experiencing.

When using multithreading, the two segments are fed to two individual recognizers simultaneously.

So far, the behavior you're experiencing is quite expected. What I don't understand is why the multithreaded version produces different results on OS X than on Linux.

I must confess that I'm not really an expert on speech recognition, though. I understand only parts of the inner workings of Pocketsphinx, which is what Rhubarb uses.

I'm closing the issue because I don't believe I can help you there.

**Comment by brettharrisonzya** [comment]
Thanks for your help.
