### ISSUE TITLE
Lack of documentation Adobe After Effects

### ISSUE THREAD

**Issue by pierreclr** [DanielSWolf/rhubarb-lip-sync#64]
Hi, 

I'm actually encounter some difficulties to use Rhubarb in After Effect. 

Binary is installed etc, everything should work as expected but we've got the following error "No animation result, animation was probably canceled" : We have a mouth composition with A to F (on file per frame) and a wave audio file. Is there any step by step documentation that we could find ? 

Any help will be very appreciated :)

**Comment by DanielSWolf** [comment]
It's true that there is currently very little documentation for the After Effects script. I assume you already found [what little there is](https://github.com/DanielSWolf/rhubarb-lip-sync/tree/master/extras/AdobeAfterEffects); otherwise, have a look.

Even if you did something wrong, you normally shouldn't get the error message you got. What operating system are you using?

**Comment by 10by10pixel** [comment]
On MacOS I get the following
![image](https://user-images.githubusercontent.com/5394990/59224042-6314a580-8b9b-11e9-8002-c449a34ba252.png)
