### ISSUE TITLE
A build.sh for Linux would be very useful

### ISSUE THREAD

**Issue by gabrielmontagne** [DanielSWolf/rhubarb-lip-sync#86]
I'm a Python developer so I sink when I try to build this project.  The Linux prebuilt packages work great but I'd like to be able to compile my own version -- I'd like to extend the framerate _down_ to 10fps as I'm working on a stop-motion type animation.

Could you please provide the steps you use on CI as a `.sh` script?
Thanks!

**Comment by DanielSWolf** [comment]
You didn't mention what export format you're planning to use. I'll assume you'll be using one of the simple ones (CSV, JSON, ...) and process the result in Python.

Right now, animation always works with 100 fps internally. When you set the frame rate, all Rhubarb does is throw away frames to match the desired frame rate. So rather than build Rhubarb yourself, you can run it without specifying a frame rate, then do the same processing in Python. As a guide, here's [Rhubarb's downsampling code](https://github.com/DanielSWolf/rhubarb-lip-sync/blob/master/rhubarb/src/exporters/DatExporter.cpp#L48).

**Comment by gabrielmontagne** [comment]
Thanks @DanielSWolf , that's interesting and useful to know.  I'll down-sample from the 100fps on my end.  I wonder if that .sh would still be useful to have in general?  I'll be happy to decline this issue otherwise.

**Comment by DanielSWolf** [comment]
A build script for Linux would be easy to create. Basically, it should be enough to duplicate *package-osx.sh*, replacing the line `cmake .. -G Xcode` with `cmake ..`.

The thing is that I'm currently working on a major redesign, which will eventually make all these build scripts obsolete. So I'll close this issue for now. If anyone else needs a build script for Linux, just comment here and I'll add it!
